version: "3"

services:
  db:
    image: postgres
    volumes:
      - "db_data:/var/lib/postgres/data"
    environment:
      - "POSTGRES_USER=monster_discount"
      - "POSTGRES_PASSWORD=MUAo1GqZ75WBzZlBALMqr3k4uU97s1uH"
    ports:
      - 5434:5432

volumes:
  db_data:
