{
 "title": "REWE Monster notifications",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is discounted at Dieker Straße",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  discounted\nFROM scrapes\nWHERE\n  $__timeFilter(created_at)\n  AND scrapes.market_id = 1940156\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Current Price",
   "type": "stat",
   "gridPos": { "h": 17, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  price / 100.0\nFROM scrapes\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of scrapes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(1) as \"lol\"\nFROM scrapes\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of markets to scrape",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(1)\nFROM markets"
    }
   ]
  },
  {
   "title": "Monster Price at REWE Dieker Straße",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  price / 100.0\nFROM scrapes\nWHERE\n  $__timeFilter(created_at) AND\n  market_id = 1940156\nORDER BY 1"
    }
   ]
  },
  {
   "title": "scraping successful",
   "type": "stat",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  success::integer\nFROM scrapes\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}