// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAroQb6W2JXtFWgkKVjoElL4wdJOK281Ng',
    appId: '1:894615797397:web:ba22d03ff2cc404871a59c',
    messagingSenderId: '894615797397',
    projectId: 'monster-discount',
    authDomain: 'monster-discount.firebaseapp.com',
    storageBucket: 'monster-discount.appspot.com',
    measurementId: 'G-FP03CS0HHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03s_G2Lvc_98KV44xIojfAjcYbQwW-eU',
    appId: '1:894615797397:android:ae0e008fecc4971f71a59c',
    messagingSenderId: '894615797397',
    projectId: 'monster-discount',
    storageBucket: 'monster-discount.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYII_Jm-qasVYVNlEN5iqbXrBei4jX5t4',
    appId: '1:894615797397:ios:4290e9ccb86f5ab971a59c',
    messagingSenderId: '894615797397',
    projectId: 'monster-discount',
    storageBucket: 'monster-discount.appspot.com',
    iosClientId: '894615797397-q6ucujlse55r70mniohc8t5eds44f7ko.apps.googleusercontent.com',
    iosBundleId: 'xyz.ente.app',
  );
}
